variables:
  FAULTED_TESTS_PUBLISHER: 'E:\Work\Trx\Release\ParseTrx.bat'
  TEST_RESULT_DIR: 'TestResults'
stages:
  - build
  - test
build:
  stage: build
  only:
    - branches  
  script:
    - '& dotnet build --configuration Release /clp:ErrorsOnly'
  artifacts:
    untracked: true
    expire_in: 2 days
    paths: 
      - 'TestResults\'
test:
  stage: test
  script:
    - '& dotnet test --filter "FullyQualifiedName~TestCryptoApis.Exchanges
      |FullyQualifiedName~TestCryptoApis.Blockchains.Info
      |FullyQualifiedName~TestCryptoApis.Blockchains.WebhookNotifications
      |FullyQualifiedName~TestCryptoApis.Blockchains.Addresses
      |FullyQualifiedName~TestCryptoApis.Blockchains.Contracts
      |FullyQualifiedName~TestCryptoApis.Blockchains.PaymentForwardings
      |FullyQualifiedName~TestCryptoApis.Blockchains.Wallets" --no-build --results-directory "$env:TEST_RESULT_DIR" --logger trx --verbosity quiet --configuration Release'
  retry: 2
  dependencies:
    - build
  after_script:
    - '& "$env:FAULTED_TESTS_PUBLISHER" "$env:TEST_RESULT_DIR"'