variables:
  NUGET_PATH: 'D:\Program Files (x86)\nuget.exe'
  PROJECT_NAME: 'CryptoApisSdkLibrary'
  TEST_PROJECT_NAME: 'TestCryptoApiSdk'
  FAULTED_TESTS_PUBLISHER: 'E:\Work\Trx\Release\ParseTrx.bat'
  TEST_RESULT_DIR: 'TestResults'
stages:
  - build
  - test
build:
  stage: build
  only:
    - branches  
  script:
    - '& "$env:NUGET_PATH" restore'
    - '& dotnet build --configuration Release /clp:ErrorsOnly'
  artifacts:
    untracked: true
    expire_in: 2 days
    paths: 
      - 'TestResults\'
test:
  stage: test
  script:
    #- '& dotnet test --filter FullyQualifiedName~TestCryptoApiSdk.Exchanges --no-build --results-directory "$env:TEST_RESULT_DIR" --logger trx --verbosity quiet --configuration Release'
    - '& dotnet test --filter "FullyQualifiedName~TestCryptoApiSdk.Exchanges|FullyQualifiedName~TestCryptoApiSdk.Blockchains.Info" --no-build --results-directory "$env:TEST_RESULT_DIR" --logger trx --verbosity quiet --configuration Release'
  dependencies:
    - build
  after_script:
    - '& "$env:FAULTED_TESTS_PUBLISHER" "$env:TEST_RESULT_DIR"'
#