variables:
  NUGET_PATH: 'D:\Program Files (x86)\nuget.exe'
  PROJECT_NAME: 'CryptoApisSdkLibrary'
  TEST_PROJECT_NAME: 'TestCryptoApiSdk'
  FAULTED_TESTS_PUBLISHER: 'E:\Work\Trx\Release\ParseTrx.bat'
  TEST_RESULT_DIR: 'TestResults'
stages:
  - build
  - test
  - publishing
build:
  stage: build
  only:
    - branches  
  script:
  - echo "Restoring NuGet Packages... "
  # wwwww
  - '& "$env:NUGET_PATH" restore'
  - echo "Release build..."
  - '& dotnet build --configuration Release /clp:ErrorsOnly'
  artifacts:
    untracked: true
    expire_in: 2 days
test:
  stage: test
  before_script:
  - echo "Removing old session results..."
  - if (Test-Path "$env:TEST_PROJECT_NAME\$env:TEST_RESULT_DIR") { Remove-Item "$env:TEST_PROJECT_NAME\$env:TEST_RESULT_DIR" -Recurse -Force }
  script:
  - echo "Starting tests..."
  - cd "$env:TEST_PROJECT_NAME"
  #- '& dotnet test --filter FullyQualifiedName~TestCryptoApiSdk.Exchanges.Test --no-build --results-directory "$env:TEST_RESULT_DIR" --configuration Release --logger trx --verbosity quiet'
  - '& dotnet test --filter FullyQualifiedName~TestCryptoApiSdk.Exchanges.Test --no-build --results-directory "$env:TEST_RESULT_DIR" --logger trx --verbosity quiet'
  - '& dotnet test --filter FullyQualifiedName~TestCryptoApiSdk.Exchanges.Test2 --no-build --results-directory "$env:TEST_RESULT_DIR" --logger trx --verbosity quiet'
  dependencies:
  - build
  artifacts:
    path:
    - TestResults/
    expire_in: 5 mins
publishing:
  stage: publishing
  script:
  - echo "Starting publishing test results..."
  - '& "$env:FAULTED_TESTS_PUBLISHER" "$env:TEST_PROJECT_NAME\$env:TEST_RESULT_DIR"'
  dependencies:
  - test