variables:
  NUGET_PATH: 'D:\Program Files (x86)\nuget.exe'
  MSBUILD_PATH: 'c:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.exe'
  PROJECT_NAME: 'CryptoApisSdkLibrary'
  TEST_PROJECT_NAME: 'TestCryptoApiSdk'
  FAULTED_TESTS_PUBLISHER: 'E:\Work\Trx\Release\ParseTrx.bat'
before_script:
  - Remove-Item "$env:TEST_PROJECT_NAME"\TestResults -Recurse
stages:
  - build
  - test
build:
  stage: build
  only:
    - branches  
  script:
  - echo "Restoring NuGet Packages... "
  - '& "$env:NUGET_PATH" restore'
  - echo "Release build..."
  - '& "$env:MSBUILD_PATH" /p:Configuration=Release /clp:ErrorsOnly'
  artifacts:
    untracked: true
    expire_in: 2 days
test:
  stage: test
  script:
  - echo "Starting tests..."
  - cd "$env:TEST_PROJECT_NAME"
  - dotnet test --filter FullyQualifiedName~TestCryptoApiSdk.Exchanges.Test --no-build --results-directory TestResults --configuration Release --logger trx --verbosity quiet
  after_script:
  - '& "$env:FAULTED_TESTS_PUBLISHER" "$env:TEST_PROJECT_NAME\bin\Release\$env:TRX_FILENAME"'
  dependencies:
  - build